### ISSUE TITLE
How can i load my model to predict new data?

### ISSUE THREAD

**Issue by hoabuiduy** [undertheseanlp/classification#8]
Hi,
I created my model.bin and save to tmp dir
how can i predict new data using my model?

Thanks

**Comment by rain1024** [comment]
@hoabuiduy, sorry because I answer a little bit late. I'm too busy right now, so I'm going to fix this issue next 2 weeks. 

In case you can carry it on your self. Its idea is simple. After train model by these following command

```
$ python train.py --mode train \
     --train data/VNTC/corpus/train \
     -s tmp/model.bin 
```

You must load `model.bin` file in to [fasttext] using [these command](https://github.com/pyk/fastText.py#load-pre-trained-classifier)

```
classifier = fasttext.load_model('model.bin')
```

Finally, you can use fasttext model to predict label of new text

```
labels = classifier.predict(texts, k)
```

**Comment by hoabuiduy** [comment]
Thanks @rain1024 
More question: Does your lib support append / update existing model?

**Comment by rain1024** [comment]
Do you mean `underthesea`? It has not yet these feature. I will consider to add these feature in the future

**Comment by hoabuiduy** [comment]
Yes,
Thanks for your support

**Comment by thuvh** [comment]
bạn có thể tạo pull request mà?
